<?php /** @var \Indexiz\AdminCustomizer\Block\Page\Copyright $block */ ?>

<?php if ($block->isModuleEnabled() && $block->canChangeCopyright() ): ?>
   
        <?= $block->escapeHtml($block->getCustomCopyright()) ?>
   
<?php else: ?>
    <a class="link-copyright" href="http://magento.com" target="_blank" title="<?= $block->escapeHtmlAttr(__('Magento')) ?>"></a>
    <?= $block->escapeHtml(__('Copyright &copy; %1 Magento Commerce Inc. All rights reserved.', date('Y'))) ?>
<?php endif; ?>
